#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "gcc -fPIC -DOPENSSL_PIC -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -I/home/billones1977/.rvm/usr/include -DL_ENDIAN -DTERMIO -O3 -fomit-frame-pointer -Wall"
  #define PLATFORM "linux-elf"
  #define DATE "Wed Feb 23 14:11:08 EST 2011"
#endif
